# Site settings
author: Bryce Eadie
title: My Blog
header-img: img/home-bg.png
email: bryce.eadie@gmail.com
copyright_name: Bryce Eadie
description: > # this means to ignore newlines until "baseurl:"
  about stuff
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  buraizu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
